apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr
spec:
  project: default
  source:
    repoURL: https://github.com/kata-kas/home-lab.git
    path: apps/homarr
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
